### ISSUE TITLE
Cannot Get the Model

### ISSUE THREAD

**Issue by mntalha** [meta-llama/llama#1036]
As a PhD student, I have applied to access the llama model and I couldn't get any response for nearly a week. In the Hugging Face, it says " Requests will be processed in 1-2 days.".  

My Hugging Face email and email that I wrote down on the Meta website is the same. 

So, is there any problem for accessing  [meta-llama/Llama-2-7b](https://huggingface.co/meta-llama/Llama-2-7b) ?

**Comment by Joseph2001-braganza** [comment]
Hi @mntalha I tried downloading today using this link https://llama.meta.com/llama-downloads/
then I instantly got the steps to move forward along with its download !

**Comment by mntalha** [comment]
Hi, 

Interesting,  which models did you choose to access? I chose all in my application.

**Comment by Joseph2001-braganza** [comment]
Hello 
Same even I chose all the models !

**Comment by jspisak** [comment]
Please try again and let us know if it doesn't work. We are trying to streamline the approval process so it should be a lot faster.

**Comment by zorache** [comment]
Hi! I am able to download the llama2 models directly via the email/meta release form, but have not gotten HF approval. The emails I used are the same (zche@umd.edu). The HF repo I'm requesting access to is [Llama-2-7b-chat-hf](https://huggingface.co/meta-llama/).

I can't resubmit a HF access request. It's been a while (~a month?) since my HF request. Could you help me troubleshoot this?

**Comment by mntalha** [comment]
> Please try again and let us know if it doesn't work. We are trying to streamline the approval process so it should be a lot faster.

Thank you, I received an email by Meta and installed the model successfully.
